---
- name: Ensure bash_it repository is cloned locally.
  git:
    repo: "{{ bash_it_repo }}"
    dest: "{{ bash_it_repo_local_destination }}"
    version: "{{ bash_it_repo_version }}"
    accept_hostkey: "{{ bash_it_repo_accept_hostkey }}"

- name: Create init script
  template:
    src: bash_it.j2
    dest: "{{ bash_it_repo_local_destination }}.init"
