---
- name: Set configuration to dotfiles
  shell: |
    defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "{{ devstrap_base_path }}/iterm2"
    defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
