---
- name: Set configuration to dotfiles
  shell: |
    defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "{{ dotfiles_repo_local_destination }}/iterm2"
    defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
